"""add player pending production

Revision ID: 08278f5dc281
Revises: 48548e15b159
Create Date: 2026-08-04 01:25:44.530296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08278f5dc281'
down_revision = '48548e15b159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_production', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('pending_production')

    # ### end Alembic commands ###
