"""add login streak fields to player

Revision ID: 0833f8cfccc2
Revises: 5dc2a02ece17
Create Date: 2026-08-03 06:40:41.161564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0833f8cfccc2'
down_revision = '5dc2a02ece17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('login_streak')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
