"""add player stats, daily contracts, achievements

Revision ID: 106b65a0ca7d
Revises: 6b0f8ec37000
Create Date: 2026-08-03 19:47:18.213452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106b65a0ca7d'
down_revision = '6b0f8ec37000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('daily_contracts', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('achievements')
        batch_op.drop_column('daily_contracts')
        batch_op.drop_column('stats')

    # ### end Alembic commands ###
