"""add player reputation and story choices

Revision ID: 13449cf523a1
Revises: 106b65a0ca7d
Create Date: 2026-08-03 20:07:54.778121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13449cf523a1'
down_revision = '106b65a0ca7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reputation', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('story_choices', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('story_choices')
        batch_op.drop_column('reputation')

    # ### end Alembic commands ###
