"""player rested_energy reserve

Revision ID: 2447cd3ab357
Revises: a19c575b3bbb
Create Date: 2026-08-04 22:35:46.041997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2447cd3ab357'
down_revision = 'a19c575b3bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rested_energy', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('rested_energy')

    # ### end Alembic commands ###
