"""add market price trend and fair value

Revision ID: 48548e15b159
Revises: d381bfc1b275
Create Date: 2026-08-04 00:57:02.669794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48548e15b159'
down_revision = 'd381bfc1b275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_price', schema=None) as batch_op:
        # server_default is required, not cosmetic: existing market_price
        # rows have no value for a new NOT NULL column and SQLite refuses
        # the ALTER outright without one. A flat trend is the correct
        # starting state; fair_value is nullable and falls back to
        # base_cost on first tick.
        batch_op.add_column(
            sa.Column('trend', sa.Float(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('fair_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_price', schema=None) as batch_op:
        batch_op.drop_column('fair_value')
        batch_op.drop_column('trend')

    # ### end Alembic commands ###
