"""add market_price table, player item_cooldowns/last_tick_at, drop item_prices

Revision ID: 5dc2a02ece17
Revises: 6a6a331ac353
Create Date: 2026-08-02 22:59:21.313268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5dc2a02ece17'
down_revision = '6a6a331ac353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=False),
    sa.Column('current_cost', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_cooldowns', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_tick_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('item_prices')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_prices', sqlite.JSON(), nullable=True))
        batch_op.drop_column('last_tick_at')
        batch_op.drop_column('item_cooldowns')

    op.drop_table('market_price')
    # ### end Alembic commands ###
