"""add game_event table

Revision ID: 676cbd03c770
Revises: 93f7afc9b648
Create Date: 2026-08-03 07:08:55.108329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676cbd03c770'
down_revision = '93f7afc9b648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_event')
    # ### end Alembic commands ###
