"""add player win_streak

Revision ID: 6b0f8ec37000
Revises: c2c1fa5d85d1
Create Date: 2026-08-03 19:36:02.012870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0f8ec37000'
down_revision = 'c2c1fa5d85d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('win_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('win_streak')

    # ### end Alembic commands ###
