"""add prestige level to player

Revision ID: 93f7afc9b648
Revises: 0833f8cfccc2
Create Date: 2026-08-03 06:56:30.203672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f7afc9b648'
down_revision = '0833f8cfccc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prestige_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('prestige_level')

    # ### end Alembic commands ###
