"""player recovery_uses daily medlab counters

Revision ID: a19c575b3bbb
Revises: e0ab4b0aa92f
Create Date: 2026-08-04 22:09:03.773844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19c575b3bbb'
down_revision = 'e0ab4b0aa92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_uses', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('recovery_uses')

    # ### end Alembic commands ###
