"""passive tick clocks, equipment cap, upgrade steps, price history

Revision ID: c2c1fa5d85d1
Revises: dc1daf6db6a6
Create Date: 2026-08-03 17:40:24.359553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c1fa5d85d1'
down_revision = 'dc1daf6db6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=80), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_price_history_item_name'), ['item_name'], unique=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maxEquipmentCount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upgrade_steps', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_energy_tick_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_health_tick_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_production_tick_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_trickle_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('last_trickle_at')
        batch_op.drop_column('last_production_tick_at')
        batch_op.drop_column('last_health_tick_at')
        batch_op.drop_column('last_energy_tick_at')
        batch_op.drop_column('upgrade_steps')
        batch_op.drop_column('maxEquipmentCount')

    with op.batch_alter_table('market_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_price_history_item_name'))

    op.drop_table('market_price_history')
    # ### end Alembic commands ###
