"""add player production remainders

Revision ID: d381bfc1b275
Revises: 13449cf523a1
Create Date: 2026-08-03 23:44:55.058344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd381bfc1b275'
down_revision = '13449cf523a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_remainders', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('production_remainders')

    # ### end Alembic commands ###
