"""add activity log entry table and market price last_notified_cost

Revision ID: dc1daf6db6a6
Revises: 676cbd03c770
Create Date: 2026-08-03 16:50:30.956595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1daf6db6a6'
down_revision = '676cbd03c770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_notified_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_price', schema=None) as batch_op:
        batch_op.drop_column('last_notified_cost')

    op.drop_table('activity_log_entry')
    # ### end Alembic commands ###
