"""add player ship modules

Revision ID: e0ab4b0aa92f
Revises: 08278f5dc281
Create Date: 2026-08-04 02:40:36.286817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ab4b0aa92f'
down_revision = '08278f5dc281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('ship')

    # ### end Alembic commands ###
